name: gphil
description: 'Your Personal Orchestra'
publish_to: 'none'
version: 0.1.3
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  path_provider: ^2.1.3
  intl: ^0.19.0
  http: ^1.2.1
  signals: ^5.2.0
  connectivity: ^3.0.2
  flutter_soloud: ^2.0.2
  # flutter_rust_bridge: 2.1.0
  # rust_lib_gphil:
  #   path: rust_builder
  syncfusion_flutter_sliders: ^26.2.7
  syncfusion_flutter_core: ^26.2.7
  syncfusion_flutter_pdfviewer: ^26.2.7
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.2
  dio: ^5.5.0+1
  file_picker: ^8.0.0+1
  # background_downloader: ^8.5.3
  # desktop_multi_window: ^0.2.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.13.1
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-Bold.ttf
          weight: 700

flutter_launcher_icons:
  # android: "launcher_icon"
  # ios: true
  image_path: 'assets/images/gphil_icon.png'
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    # generate: true
    # image_path: 'assets/gphilicon.png'
    background_color: '#hexcode'
    theme_color: '#hexcode'
  windows:
    generate: true
    image_path: 'assets/images/gphil_icon.png'
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: 'assets/images/gphil_icon.png'
