name: gphil
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  audioplayers: ^6.0.0
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_cors: ^1.5.0
  flutter_sanity: ^1.1.0
  flutter_sanity_image_url: ^0.1.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  google_fonts: ^4.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
    - assets/fonts/
