name: gphil
description: "Your Personal Orchestra"
publish_to: "none"
version: 1.0.1-beta
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  path_provider: ^2.1.3
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  flutter_soloud: ^2.0.2
  syncfusion_flutter_sliders: ^28.1.33
  syncfusion_flutter_core: ^28.1.33
  syncfusion_flutter_pdfviewer: ^28.1.33
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.2
  dio: ^5.5.0+1
  file_picker: ^8.0.0+1
  connectivity_plus: ^6.0.5
  internet_connection_checker_plus: ^2.5.1
  idb_shim: ^2.6.1
  cached_network_image: ^3.4.1
  logging: ^1.2.0
  flutter_svg: ^2.0.16
  window_manager: ^0.4.2
  sanity_client: ^1.4.2
  path: ^1.9.0
  http: ^1.2.2
  http_parser: ^4.1.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  google_fonts: ^6.2.1
  mockito: ^5.4.2
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.14.1
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
    - fonts/
    - shorebird.yaml

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-Bold.ttf
          weight: 700

flutter_launcher_icons:
  # android: "launcher_icon"
  # ios: true
  image_path: "assets/images/gphil_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/gphil_icon.png"
    # background_color: '#hexcode'
    # theme_color: '#hexcode'
  windows:
    generate: true
    image_path: "assets/images/gphil_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/gphil_icon.png"
