name: gphil
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  audioplayers: ^6.0.0
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_cors: ^1.5.0
  flutter_distributor: ^0.4.0
  flutter_sanity: ^1.1.0
  flutter_sanity_image_url: ^0.1.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  path_provider: ^2.1.3
  intl: ^0.19.0
  http: ^0.13.4

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  google_fonts: ^4.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
    - fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-Bold.ttf
          weight: 700